server:
  port: 9527
  servlet:
    context-path: /pk-spark-web

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pk
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 0

hbase:
  zookeeper:
    quorum: localhost
    property:
      clientPort: 2181

zookeeper:
  znode:
    parent: /hbase

